import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'
import HeaderMenu from '@/components/HeaderMenu'

const inter = Inter({ subsets: ['latin'] })

const headerStyle = 'text-3xl, font-bold'

export default function Home() {
  return (
    <>
      <Head>
        <title>LoLFans</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeaderMenu />

      <main className={styles.main}>
        <h1 className={headerStyle}>LoLfans</h1>
      </main>
    </>
  )
}
